[package]
name = "luxrec-portal"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
luxrec-core = { path = "../luxrec-core" }
tokio.workspace = true
ashpd.workspace = true
tracing.workspace = true
thiserror.workspace = true
